apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  labels:
    app: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
        - name: content-service
          image: pasamentiregistry.azurecr.io/content_service:latest # Sostituisci con l'immagine Docker del content service
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://content-mongodb:27017/contentdb" # Sostituisci con la connessione al database

---
apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  type: NodePort
  selector:
    app: content-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
