apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-mongodb
  labels:
    app: content-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-mongodb
  template:
    metadata:
      labels:
        app: content-mongodb
    spec:
      containers:
        - name: content-mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: content-mongodb
spec:
  type: ClusterIP
  selector:
    app: content-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017